// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("elasticapmconnector")
)

const (
	TracesToMetricsStability  = component.StabilityLevelDevelopment
	MetricsToMetricsStability = component.StabilityLevelDevelopment
	LogsToMetricsStability    = component.StabilityLevelDevelopment
)
